<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ABRU889D" failures="1" tests="3" name="Test" time="7.614" errors="0" timestamp="2025-08-30T15:56:39 IST">
  <testcase classname="tests.LoginTest" name="loginTest" time="6.434">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [Failure]
at tests.LoginTest.loginTest(LoginTest.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.LoginTest" name="loginTest" time="0.031">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.LoginTest" name="loginTest" time="0.024">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test -->
